"""create tenants

Revision ID: 6b3ee0ec366c
Revises: f3afb0757d35
Create Date: 2026-02-18 07:05:42.275000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b3ee0ec366c'
down_revision: Union[str, Sequence[str], None] = 'f3afb0757d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_email'))
        batch_op.create_index(batch_op.f('ix_clients_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_email'))
        batch_op.create_index(batch_op.f('ix_clients_email'), ['email'], unique=1)

    # ### end Alembic commands ###
